databases:
  - name: pareto-listing
    databaseName: pareto-listing
    user: pareto-listing
    plan: free

services:
  - type: web
    name: pareto-listing
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pareto-listing
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default